"""Add Google Ads tracking fields

Revision ID: 174602ca6cd5
Revises: e35ef13e5504
Create Date: 2025-11-30 00:14:13.543672

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '174602ca6cd5'
down_revision = 'e35ef13e5504'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('signup_gclid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('signup_gbraid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('signup_wbraid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('last_checkout_gclid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('last_checkout_gbraid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('last_checkout_wbraid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'last_checkout_wbraid')
    op.drop_column('user_profiles', 'last_checkout_gbraid')
    op.drop_column('user_profiles', 'last_checkout_gclid')
    op.drop_column('user_profiles', 'signup_wbraid')
    op.drop_column('user_profiles', 'signup_gbraid')
    op.drop_column('user_profiles', 'signup_gclid')
    # ### end Alembic commands ###

