"""add_snap_tracking_fields

Revision ID: 4b6f2a985583
Revises: 174602ca6cd5
Create Date: 2025-12-03 17:21:33.564238

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4b6f2a985583'
down_revision = '174602ca6cd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('signup_sc_cookie1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('signup_sc_clid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('last_checkout_sc_cookie1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('last_checkout_sc_clid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'last_checkout_sc_clid')
    op.drop_column('user_profiles', 'last_checkout_sc_cookie1')
    op.drop_column('user_profiles', 'signup_sc_clid')
    op.drop_column('user_profiles', 'signup_sc_cookie1')
    # ### end Alembic commands ###

