"""add_signup_tracking_context

Revision ID: 4b7e6c701840
Revises: add_subscription_fields
Create Date: 2025-11-23 23:24:26.806401

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4b7e6c701840'
down_revision = 'add_subscription_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_codes_code'), 'password_reset_codes', ['code'], unique=False)
    op.create_index(op.f('ix_password_reset_codes_email'), 'password_reset_codes', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_codes_used'), 'password_reset_codes', ['used'], unique=False)
    op.alter_column('subscriptions', 'last_credit_reset',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('user_profiles', sa.Column('signup_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('signup_user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('signup_fbp', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('signup_fbc', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'signup_fbc')
    op.drop_column('user_profiles', 'signup_fbp')
    op.drop_column('user_profiles', 'signup_user_agent')
    op.drop_column('user_profiles', 'signup_ip')
    op.alter_column('subscriptions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'last_credit_reset',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_password_reset_codes_used'), table_name='password_reset_codes')
    op.drop_index(op.f('ix_password_reset_codes_email'), table_name='password_reset_codes')
    op.drop_index(op.f('ix_password_reset_codes_code'), table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    # ### end Alembic commands ###

