"""add_tiktok_tracking_fields

Revision ID: e35ef13e5504
Revises: update_trial_credits_to_40
Create Date: 2025-11-29 02:43:40.133660

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e35ef13e5504'
down_revision = 'update_trial_credits_to_40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('signup_ttp', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('signup_ttclid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('last_checkout_ttp', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profiles', sa.Column('last_checkout_ttclid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user_profiles', 'last_checkout_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'last_checkout_timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('user_profiles', 'last_checkout_ttclid')
    op.drop_column('user_profiles', 'last_checkout_ttp')
    op.drop_column('user_profiles', 'signup_ttclid')
    op.drop_column('user_profiles', 'signup_ttp')
    # ### end Alembic commands ###

